### ISSUE TITLE
[Feature]: 请问，考虑支持api，和临时账户吗？ 比如将某个资源临时开放给临时账户？

### ISSUE THREAD

**Issue by xjdata** [veops/oneterm#21]
### What is your advice?

everyone wants this feature!

### Version

newest

**Comment by ttktatakai** [comment]
@xjdata 临时账户可以计划一下，api具体是指？

**Comment by xjdata** [comment]
谢谢你的回复，我是一些具体的要求。 不知道是否可以考虑。

我的使用场景： 假设我有 100 个 虚拟服务器， 今天希望给200个用户使用。 明天希望给 新的300个客户使用。 现在手工做这些太麻烦了，  如果可以api方式实现， 每个账户可以使用哪个服务器，每个账户可以使用多久等等  对我来说那就太方便了。 


api 支持  新增用户，新增授权

用户支持 限定 起止时间。

windows 支持 远程过程的录像。

**Comment by ttktatakai** [comment]
@xjdata 
有些点可能需要在确认下
1. 这些临时账户是否需要登录oneterm的页面（因为能登录到oneterm的界面需要一个ACL的账号）
2. 对于这个链接，点击后是直接进入ssh页面还是需要进行资产选择（即一个链接对应一台机器还是对应多台）

**Comment by xjdata** [comment]
@ttktatakai  谢谢。

1.  这些账户都不需要登录 oneterm 的页面，  相当于 有个 一次性 token 的url ， 使用一次后就作废了。  这个链接直接可以控制 windows
2. 不需要选择， 肯定是唯一的虚拟机

谢谢你

**Comment by ttktatakai** [comment]
@xjdata temp link is supported now
