### ISSUE TITLE
[Bug]: 主干的代码是最新的吗

### ISSUE THREAD

**Issue by a1235** [veops/oneterm#30]
### This bug is related to UI or API?

API

### What happened?

![image](https://github.com/veops/oneterm/assets/29188013/435d8201-9ac8-4426-81da-171e9fef704f)
"api/common-setting/v1/auth_config/enable_list" 这个接口本地运行时为啥404了

### Version

newest

**Comment by ttktatakai** [comment]
@a1235 
1. main分支是最新代码（开发分支），稳定分支会有tag
2. 这个接口应该是由cmdb-api提供，可以使用 https://github.com/veops/OneOps-deploy 这个项目部署cmdb+oneterm
3. 如果使用2的方式还是有问题，可以提供一下您部署的详细流程
